name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Publish udagram-api-feed to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-api-feed
          push: true
          tags: quentinsop/udagram-api-feed:latest, quentinsop/udagram-api-feed:${{ github.run_number }}
          
      - name: Publish udagram-api-user to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-api-user
          push: true
          tags: quentinsop/udagram-api-user:latest, quentinsop/udagram-api-user:${{ github.run_number }}
          
      - name: Publish udagram-frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-frontend
          push: true
          tags: quentinsop/udagram-frontend:latest, quentinsop/udagram-frontend:${{ github.run_number }}
          
      - name: Publish reverseproxy to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./udagram-reverseproxy
          push: true
          tags: quentinsop/reverseproxy:latest, quentinsop/reverseproxy:${{ github.run_number }}
